{% set name = "libgit2" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8c1eaf0cf07cba0e9021920bfba9502140220786ed5d8a8ec6c7ad9174522f8e
  patches:
    # TODO: Propose this patch to upstream.
    # Downside: This breaks pkg-config for static builds (not relevant for conda-forge).
    - 0001-Use-Requires.internal-instead-of-Requires.private.patch

build:
  number: 0
  run_exports:
    # SONAME is based on minor version
    - {{ pin_subpackage("libgit2", max_pin="x.x") }}

requirements:
  build:
    - cmake
    - ninja
    - pkg-config      # [not win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes      # [win]
    - openssl         # [not win]
    - libiconv        # [osx]
    - pcre2  # [unix]
    - curl
    - libssh2
    - zlib

test:
  requires:
    - pkg-config
  commands:
    - test -f $PREFIX/include/git2.h                 # [not win]
    - if not exist %LIBRARY_INC%\\git2.h exit 1      # [win]
    - test -f $PREFIX/lib/libgit2${SHLIB_EXT}        # [unix]
    - if not exist %LIBRARY_LIB%\\git2.lib exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\git2.dll exit 1    # [win]
    - pkg-config --cflags --libs libgit2

about:
  home: https://libgit2.github.com
  license: GPL-2.0-only WITH GCC-exception-2.0
  license_file: COPYING
  summary: libgit2 is a portable, pure C implementation of the Git core methods provided as a re-entrant linkable library with a solid API, allowing you to write native speed custom Git applications in any language which supports C bindings.

  # The remaining entries in this section are optional, but recommended
  description: |
    libgit2 is a portable, pure C implementation of the Git core methods
    provided as a re-entrant linkable library with a solid API, allowing
    you to write native speed custom Git applications in any language
    which supports C bindings.

extra:
  recipe-maintainers:
    - shadowwalkersb
    - xhochy
